dist: trusty
sudo: false

language: c

os:
  - linux

compiler:
  - gcc

addons:
  apt:
    sources:
      - ubuntu-toolchain-r-test
    packages:
      - gcc-4.9

env:
  - TARGET_CPU=amd64 BUILD_CONFIGURATION=Debug

script:
  # Export CC to tell cmake which compiler to use
  - export CC=gcc-4.9
  # Check versions of gcc and cmake
  - gcc -v
  - cmake --version
  # Build
  - mkdir build
  - cd build
  - cmake .. -DCMAKE_BUILD_TYPE=$BUILD_CONFIGURATION -DTARGET_CPU=$TARGET_CPU
  - cmake --build .